### PR TITLE
feat: add antialiased class to template layout, component stories

### PR DESCRIPTION
**Pull request by karrui**
### TL;DR

Added `antialiased` tailwind class to improve text rendering and updated Storybook configuration.

### What changed?

- Added an antialiased class to the body element in the root layout.
- Created a LayoutDecorator for Storybook to apply the antialiased class.
- Updated Tailwind configuration to include Storybook files in the content array.
- Removed unnecessary fragment in the Page component.
- Updated generateMetadata function parameter name.

### How to test?

1. Run the application and verify that text rendering is smoother across all pages.
2. Launch Storybook and confirm that components are displayed with antialiased text.
3. Check that Tailwind styles are correctly applied to Storybook components.

### Why make this change?

The antialiased class improves text rendering, making it smoother and more readable across different browsers and devices. Including Storybook files in the Tailwind configuration ensures consistent styling in the component library. These changes enhance the overall visual quality and consistency of the application and its documentation.

### CODE REVIEW

**Comment by karrui** [comment]
* **#588** <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @karrui and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by seaerchin — APPROVED** [review]

**Comment by karrui** [comment]
why chromatic no change??!!

**Comment by karrui** [comment]
because it only works on macos lol. @sehyunidaaa FYI.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth

**Comment by sehyunidaaa** [comment]
Lol okay i guess it was only a mac problem!!

**Pull request merged**
