### PR TITLE
add flex-grow to the collection content area

### PR DESCRIPTION
**Pull request by sehyunidaaa**
## Problem

When both title and description is short, the image is misaligned
image

Closes [ISOM-1663]

## Solution

Added `flex-grow` to the title / description div.

After:
image

### CODE REVIEW

**Comment by sehyunidaaa** [comment]
Please don't merge after review, I need to check Storybook

**Review by adriangohjw — APPROVED** [review]
nit - this works but adding `justify-between` to line 40 might be better

**Comment by adriangohjw** [comment]
@sehyunidaaa lemme know if you need me to take over the storybook stuff to free up your time for design work 😄

**Comment by sehyunidaaa** [comment]
@adriangohjw sorry I was tardy with this T_T justify-between didn't work, did you mean put it on top of the flex-grow?

And yes please if you'd like to test out different string lengths!

**Pull request merged**
