### PR TITLE
feat(components): return navbar spacing and logo sizing back to original

### PR DESCRIPTION
**Pull request by sehyunidaaa**
Previously, logo spacing was too tight

- Change logo sizing and spacing 
- Add realistic test cases

### CODE REVIEW

**Comment by karrui** [comment]
tests fail, you need update them to point to the new navbar items hehe

**Review by karrui — APPROVED** [review]
lgtm, please ownself review ownself for Chromatic. Tests failing because previous interaction test was clicking `About us` button, which has now been renamed to `Max 70 chars`

**Comment by seaerchin** [comment]
thx kween

**Comment by sehyunidaaa** [comment]
Oops will adjust the tests! Not ready to merge yet

**Comment by sehyunidaaa** [comment]
sorry thought I saw a pixel inching problem on local, it doesn't seem to be happening anymore! apologies for keeping this open for so long

**Pull request merged**
