### PR TITLE
feat: implement nanoid for User model and adjust User schema

### PR DESCRIPTION
**Pull request by karrui**
## Solution

**Breaking Changes**

- [x] Yes - this PR contains breaking changes
  - The `User` model has been modified, removing the `preferredName` field and making the `phone` field optional

**Features**:

- Added `nanoid()` and `nanoid_optimized()` functions to generate compact, URL-friendly unique identifiers in Postgres

**Improvements**:

- Updated the `User` model to use `nanoid()` for ID generation instead of `cuid()`
- Removed the `@paralleldrive/cuid2` dependency

**Bug Fixes**:

- None

## Before & After Screenshots

N/A

## Tests

- Run database migrations to apply the new schema changes
- Test user creation and retrieval to ensure the new ID generation works correctly
- Verify that existing user-related functionality still works with the updated `User` model

**New scripts**:

None

**New dependencies**:

None

**New dev dependencies**:

None

### CODE REVIEW

**Comment by karrui** [comment]
* **#709** <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/709?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @karrui and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by seaerchin — COMMENTED** [review]
why use `nanoid` over `uuidv4`, which is already [implemented](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#uuid) in prisma ah?

**Comment by seaerchin** [comment]
based off what i found, the main advantage is size? but not too sure how important this is .-.

image

**Comment by karrui** [comment]
> why use `nanoid` over `uuidv4`, which is already [implemented](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#uuid) in prisma ah?

Because we are moving away from prisma right? Prisma's `uuid()` function is app-level, means if we use kysely it won't actually be generated. This PR adds in a DB-level generation

**Comment by karrui** [comment]
but actually i think i'll just use pg's `gen_random_uuid` instead of mucking around with a custom extension haha. let me update this PR

**Comment by karrui** [comment]
actually dropping it, sian now i feel the pain of using pglite. When need to add extensions you cry. They don't support pgcrypto yet. let me just update user schema to not have the fields that we don't expect.

**Pull request closed without merging**
