### PR TITLE
feat(studio): allow admins to change preview viewport size

### PR DESCRIPTION
**Pull request by karrui**
## Problem

Closes ISOM-1512

## Solution

This PR introduces a new viewport control feature for the page preview in the editing experience.

**Breaking Changes**

- [x] No - this PR is backwards compatible

**Features**:

- Added a new IframeToolbar component with viewport control options (desktop, mobile, tablet, responsive)
- Implemented viewport switching functionality in the EditPagePreview component

**Improvements**:

- Enhanced the PreviewIframe component to support different viewport sizes
- Refactored the EditPagePreview component to include the new IframeToolbar
- Updated the page editing layout to use the new EditPagePreview component

## Before & After Screenshots
See storybook

## Tests

- Test the new IframeToolbar component
- Verify that viewport switching works correctly for all options
- Ensure that the preview renders correctly in different viewport sizes
- Check that the EditPagePreview component integrates well with the existing editing experience

### CODE REVIEW

**Comment by karrui** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/658?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#658** <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/658?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#656** <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/656?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @karrui and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by harishv7 — COMMENTED** [review]
lgtm! But i think @sehyunidaaa had some comments from design wise

**Review by seaerchin — APPROVED** [review]
lgtm. one minor question, how come we need the `Portal` when rendering a full screen view?

**Comment by karrui** [comment]
> lgtm. one minor question, how come we need the `Portal` when rendering a full screen view?

If don't use portal will kena z-index shenanigans because of the various menus and tooltips.

See https://v2.chakra-ui.com/community/recipes/z-index

**Pull request merged**
