### PR TITLE
feat(CreatePageModal): add form validation and expected behaviour for modal

### PR DESCRIPTION
**Pull request by karrui**
Closes ISOM-1248

#### TL;DR

Update PageCreateModal component with the expected page URL generation behavior and form validation.

#### What changed?

- Created `PageCreateModal.stories.tsx` for Storybook configurations
- Added form validation using Zod schemas
- Enhanced Page URL generation logic
- Updated Chakra UI modal theme configuration

#### How to test?

1. Open the Storybook interface.
2. Navigate to `Components/PageCreateModal` stories.
3. Verify that the PageCreateModal component renders correctly.
4. Test the form validation and URL generation.

#### Why make this change?

This change adds the necessary modal component for creating new pages within the application, improving the user experience for adding pages.

---

### CODE REVIEW

**Comment by karrui** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/298?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#298** <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/298?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#297** <a href="https://app.graphite.dev/github/pr/opengovsg/isomer/297?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @karrui and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by seaerchin — APPROVED** [review]
lgtm! putting things down here i liked so that other engineers can learn:
1. usage of `zodForm` so that schema is inherently tied into the form
2. sharing of schema across FE/BE so validation is equal
3. usage of `key` to trigger re-render instead of having to manage state manually
4. test ot check for weird chars

some things i thought we could improve on but i'm ok with for now:
1. loose coupling between `Input#onChange` and the actual schema -> we're transforming the input so it'll pass our schema. it'd be great if we could tie this back to our schema (maybe we give a transform property?) but i'm ok w/ this now. practically speaking, idt we'll change the input validation much and we don't have attack vectors cos backend holds the strict version. (but we need to feedback error message otherwise user ripge in this case)
2. we appear to have set up tests but not too sure if we have a way to validate the result? my thinking is that tests have value when we automate and see them fail - if we rely on manual human checks, it's quite likely that this gets skipped which diminishes the value of this test.

**Comment by karrui** [comment]
added tests for frontend snapshot at least, so if it ever changes then our onChange has changed. Github Action never trigger here because first build auto-accepted... Can see at [Storybook](https://66543928751c844d159a31ef-jtdnmcjgvv.chromatic.com/?path=/story/components-pagecreatemodal--autogenerate-page-url).

**Comment by karrui** [comment]
### Merge activity

* **Jul 11, 5:29 AM EDT**: @karrui started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/opengovsg/isomer/298).

**Pull request merged**
